- hosts: all
  gather_facts: true      # Automatically retrieves system facts
  become: true          # Enables privilege escalation (sudo)

  roles:
    - install_docker    # Role responsible for installing Docker
    - create_network    # Role responsible for creating the network on which the following docker containers will be attached
    - launch_database   # Role that launches the database container
    - launch_app        # Role that launches the application API
    - launch_proxy      # Role that launches the proxy HTTPD
  