# Install prerequisites for Docker
- name: Install required packages
  apt:
    name:
      - apt-transport-https  # Required for HTTPS support
      - ca-certificates      # SSL certificates
      - curl                 # Tool for downloading files
      - gnupg                # GPG key management
      - lsb-release          # Get distribution info
      - python3-venv         # Create Python virtual environments
    state: latest
    update_cache: yes

# Add Docker’s official GPG key
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

# Add Docker repository
- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable"
    state: present
    update_cache: yes

# Install Docker engine
- name: Install Docker
  apt:
    name: docker-ce
    state: present

# Install Python and pip
- name: Install Python3 and pip3
  apt:
    name:
      - python3
      - python3-pip
    state: present

# Create Python virtual environment
- name: Create a virtual environment for Docker SDK
  command: python3 -m venv /opt/docker_venv
  args:
    creates: /opt/docker_venv

# Install Docker SDK in virtualenv
- name: Install Docker SDK for Python in virtual environment
  command: /opt/docker_venv/bin/pip install docker

# Ensure Docker service is running
- name: Make sure Docker is running
  service:
    name: docker
    state: started
  tags: docker
