name: CI devops 2025

on:
  # Launch this job on main and develop branches
  push:
    branches: 
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
      # Checkout your GitHub code using actions/checkout@v4
      - uses: actions/checkout@v4

      # Set up JDK 21 using actions/setup-java@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Build and test the app using Maven
      - name: Build and test with Maven
        run: |
          cd TP1/correction/simple-api
          mvn clean verify
          mvn -B verify sonar:sonar -Dsonar.projectKey=Marie79418_DevOps -Dsonar.organization=marie79418 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./simple-api/pom.xml

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: TP1/correction/simple-api
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/springboot-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: TP1/correction/database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/postgres_custom:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: TP1/correction/http-server
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-http-server:latest
          push: ${{ github.ref == 'refs/heads/main' }}
